/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cajero;

/**
 *
 * @author Usuario
 */
public class PantallaRetiro extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRetiro
     */
    private int monto;
    private Cajero cj = new Cajero();
    private double s;
    private static int ID=0;
    private int idRetiro;
    private int montoCajero;
    private static int MONTO_BILLETE = 20;
    
    public PantallaRetiro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    PantallaRetiro(double s, int montoCajero) {
        this.s = s;
        this.idRetiro=generarId();
        this.montoCajero = montoCajero;
        initComponents();
        addListener();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INGRESE MONTO");
        jLabel1.setToolTipText("");

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    public int actualizarSaldoCajero(int saldoCajero, int saldoRetiro){
        this.montoCajero = saldoCajero - saldoRetiro;
        return this.montoCajero;
    }
    
    public boolean cajeroSaldoSuficiente(int saldoCajero){
        return saldoCajero > 0 ? true: false;
    }
    
    public boolean esMultiplo(int montoRetiro){//tiene q ser multiplo de 20
        int resto = montoRetiro%MONTO_BILLETE;
        return resto==0 ?true: false;
       
    }
    public double RetirarEfectivo() {
        
        if (GetData() > 0) {
            try {
                double saldoNuevo= cj.Retirar(GetData(), (int) s);
                if(saldoNuevo<0){
                  JOptionPane.showMessageDialog(this, "Saldo insuficiente");
                }else if(!esMultiplo(GetData())){
                  JOptionPane.showMessageDialog(this, "Este cajero solo entrega billetes de $20, Vuelva a intentar");
                }
                else if(GetData()>10000){
                    JOptionPane.showMessageDialog(this, "Ingrese un monto menor");
                }else if(this.idRetiro==1){
                    s = saldoNuevo;
                    int saldo= actualizarSaldoCajero(10000,GetData());
                    PantallaData d = new PantallaData();
                    d.Inicio(s);
                    d.actualizarSaldoCajero(saldo);
                    d.setVisible(true);
                    return s;
                }else if(!cajeroSaldoSuficiente(this.montoCajero)){
                    JOptionPane.showMessageDialog(this, "Momentaneamente este cajero no puede entregar dinero");
                }else{
                    s = saldoNuevo;
                    int saldo = actualizarSaldoCajero(this.montoCajero,GetData());
                    PantallaData d = new PantallaData();
                    d.Inicio(s);
                    d.actualizarSaldoCajero(saldo);
                    d.setVisible(true);
                    return s;
                }
                
            } catch (Exception e) {
                e.getMessage();
            }
        } else {
            PantallaError p = new PantallaError();
            p.setVisible(true);
            this.dispose();
            return 0;
        }
        return 0;
    }
    
    
    
    public int GetData() {
        String data = this.jTextField1.getText().trim();
        if(!data.isEmpty()){
            try{
            monto = Integer.parseInt(data);
            return monto;
            }catch(Exception e){
                e.getMessage();
            }
        }
        return monto;
    }
    
    public int generarId(){
        PantallaRetiro.ID++; 
        return PantallaRetiro.ID;    
    }

    public int getIdRetiro() {
        return idRetiro;
    }
    
    private void addListener() {
        this.jButton1.addActionListener(new getDataListener());
    }
    
    private class getDataListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            RetirarEfectivo();
        }
        
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRetiro().setVisible(true);
               
            }
        });
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
